### ISSUE TITLE
License Not Defined

### ISSUE THREAD

**Issue by swalahamani** [SallyPrayerTimes/SallyPrayerTimes-Desktop#2]
السلام عليكم ورحمة الله
May Allah bless you brother,

I would like to contribute to this project. Can you please specify the license?

**Comment by bibali1980** [comment]
وعليكم السلام ورحمة الله وبركاته
May Allah bless you too
i just add GNU General Public License v3.0

**Comment by swalahamani** [comment]
Thank you.
جزاك اللهُ خيرًا
